### ISSUE TITLE
where is tty_sl?

### ISSUE THREAD

**Issue by etnt** [tonyrog/tty#1]
Hi there, I tried to run the tty_demo:start/0, got:

    1> tty_demo:start().
    ** exception error: einval
         in function  open_port/2
            called as open_port({spawn_driver,"tty_sl -c -e"},[eof])
         in call from tty_demo:demo/0 (tty_demo.erl, line 12)
         in call from tty_demo:start/0 (tty_demo.erl, line 8)

**Comment by tonyrog** [comment]
Tja!
use the -noinput -s tty_demo
tty is (re)using the user_drv low-level stuff
if you update you can also se the nice boxchar demo

**Comment by etnt** [comment]
Nice!
